### ISSUE TITLE
chef_environment support to append to environments

### ISSUE THREAD

**Issue by nukepuppy** [chef/cheffish#109]
It would be good to see chef_environment append to an environment so it is not just overwritten completely.

as in one recipe could in theory just add a specific context into the environment (for example in normal attributes)

then in another recipe to the same environment append a different context instead of overwriting all of normal attributes with what it decided.

Not sure if even feasible but never hurts to ask

**Comment by lamont-granquist** [comment]
This feels like a "not right now"

The Chef::Resource#current_value API can probably be used to retrieve the environment, then update it, then execute the action to change it.
