### ISSUE TITLE
Remove 'attributes'

### ISSUE THREAD

**Issue by jkeiser** [chef/cheffish#21]
It's a little bit confusing that

attribute 'x', 'y'

does not modify other attributes,

but attributes 'x' => 'y'

removes all other attributes.

**Comment by lamont-granquist** [comment]
It definitely feels more declarative to have an `attributes` property that fully specifies the attributes Mash, so the title of this feels certainly wrong.

**Comment by lamont-granquist** [comment]
IDK about removing `attribute` either, closing this, presumably its not super important given how stale of an issue it is.
