### ISSUE TITLE
A better Readme

### ISSUE THREAD

**Issue by mwrock** [chef/cheffish#30]
I dont think I fully understand how this gem fits in. Are there other chef technologies other than chef provisioning that use it? For example, I recently (and its not the first time) uncovered a snafu of my usage of the `complete` attribute on the `machine` resource. This is not an attribute that hangs directly off of `machine` and appears to be defined here.

Usually I look to the chef gem for core chef workings but this gem seems to sit in the middle and it would help to understand the intent behind this gem to better attack provisioning troubleshooting.

Thanks!

**Comment by poliva83** [comment]
:+1: Documentation around the resource/providers would be very helpful.

**Comment by jkeiser** [comment]
There is documentation up on chef.io, but I'm not sure where the root page is.  I'll chat with James.

**Comment by randomcamel** [comment]
Fixed.
