### ISSUE TITLE
chef group resource/provider seems broken against chef 12 server

### ISSUE THREAD

**Issue by poliva83** [chef/cheffish#38]
When creating groups the server api endpoint used is `https://localhost/groups/admins` but I keep getting back 404 errors.

[2015-02-23T17:18:30+00:00] DEBUG: Re-raising exception: Net::HTTPServerException - chef_group[admins] (bb_chef12::_manage_rbac line 65) had an error: Net::HTTPServerException: 404 "Not Found"

I think the organization endpoints used is wrong according to the docs.

https://docs.chef.io/api_chef_server.html#groups
(Request) GET /organizations/NAME/groups

https://docs.chef.io/api_chef_server.html#groups-group-name
(Request) GET /organizations/NAME/groups/GROUP_NAME

I think the LWRP needs to take in an organization name to figure out the endpoint correctly.

**Comment by andrewelizondo** [comment]
@poliva83 I've gotten around this by creating a hash with the organization I want to manage the group on.

e.g.
```ruby
config_with_org = {
  config_with_org = {
    chef_server_url: "https://server.url/organizations/myorg",
    options: {
      client_name: 'client',
      signing_key_filename: '/path/to/key'
    }
  }
}

chef_group 'admins' do
    users 'blah'
    chef_server config_with_org
end
```

**Comment by poliva83** [comment]
Thanks @andrewelizondo, @jkeiser mentioned something similar in https://github.com/chef/cheffish/pull/40#discussion_r25402834. Going to close this issue off.
