### ISSUE TITLE
Create resources for managing Chef analytics resources

### ISSUE THREAD

**Issue by andrewelizondo** [chef/cheffish#49]
As a user, I'd like to be able to specify analytics rules and notifications using cheffish opposed to creating them through the UI and/or a knife command.

I was thinking this might look something like this
e.g.

``` ruby
chef_analytics_rule 'watch-admins-group' do
  priority 0
  message :run_converge
  rule <<-EOH
  when
     #blah
  then
     #blah
  EOH
  notify 'blah'
end
```

**Comment by thommay** [comment]
Given the EOLishness of Analytics this is pretty unlikely to ever happen. We'd accept a PR, but I'm going to close out this issue for now.
