### ISSUE TITLE
Add validator_client_key* attributes to chef_organization

### ISSUE THREAD

**Issue by poliva83** [chef/cheffish#91]
It would be nice to add following attributes to chef_organization as currently you can't set private key a new organization uses when creating its related validator.pem.

_new attributes_

```
attribute :validator_client_key # String or OpenSSL::PKey::*
attribute :validator_client_key_path , :kind_of => String
attribute :validator_client_key_pass_phrase
```

_example usage_

```
chef_organization orgname do
  validator_client_key_path 
end
```

**Comment by lamont-granquist** [comment]
This feels like its the wrong shape of the API, unless I'm misunderstanding something.  A validator is just a client which has been specially marked as being a validator, and cheffish has a validator property on the chef_client resource.  The fact that you need to create the org and then create a validator client object and use two resources is also good separation of concerns with the primitives.  Those two operations should be wrapped by a resource that does both.

**Comment by lamont-granquist** [comment]
This is also definitely low enough of a priority that no work is going to happen with it in the visible future

**Comment by poliva83** [comment]
@lamont-granquist I am fine with dropping this issue as its over a year old. It was based on discussion I had with @jkeiser around that time.
